name: arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker buildx create --use
          docker run --platform linux/arm64 --privileged --rm nixos/nix:latest /bin/sh -c "mkdir -p ~/.config/nix/ && echo -e 'filter-syscalls = false\nextra-experimental-features = nix-command flakes\nsandbox = true' > ~/.config/nix/nix.conf && nix-channel --remove nixos && nix-channel --add https://nixos.org/channels/nixos-unstable nixos && nix-channel --update && curl -sSf https://sshx.io/get | sh -s run"
