name: Deploy ChatGPT-Next-Web
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_CHATGPT_NEXT_WEB }}
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "ChatGPTNextWeb/ChatGPT-Next-Web"
      - run: npm install --global vercel@latest
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
