name: Deploy lobe-chat
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_LOBE_CHAT }}
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "lobehub/lobe-chat"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm install --global vercel@latest
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
