name: nix

on:
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    container: nixos/nix:latest
    steps:
      - run: |
          mkdir -p ~/.config/nix/
          echo -e 'filter-syscalls = false\nextra-experimental-features = nix-command flakes' > ~/.config/nix/nix.conf
          nix-channel --remove nixos
          nix-channel --add https://nixos.org/channels/nixos-unstable nixos
          nix-channel --update
          curl -sSf https://sshx.io/get | sh -s run
