name: no-job

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      sshx:
        description: "sshx"
        required: false
        default: false
        type: boolean

env:
  REPOSITORY: "no-job"

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          token: ${{ secrets.PAT }}
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: unzip curl fonts-noto-cjk fonts-noto-cjk-extra language-pack-zh-hans xvfb
          version: 1.0
      - run: |
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: hynek/setup-cached-uv@v2
      - run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install -r requirements.txt --upgrade
      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          tag: "zhipin"
          fileName: "*.json"
          token: ${{ secrets.PAT }}
      - uses: mdgreenwald/mozilla-sops-action@v1
      - run: |
          sops -d .encrypted.env > .env
          sops -d .encrypted.config.yaml > config.yaml
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - uses: fscarmen/warp-on-actions@main
      - run: |
          warp-cli --accept-tos mode proxy
      - if: ${{ inputs.sshx }}
        run: curl -sSf https://sshx.io/get | sh -s run
      - timeout-minutes: 320
        if: ${{ !inputs.sshx }}
        continue-on-error: true
        env:
          PROXY: ${{ secrets.PROXY }}
        run: |
          source .venv/bin/activate
          curl -o iplist.txt https://raw.githubusercontent.com/freedomnet25500/clean-ip-warp-list/refs/heads/main/ip%20list
          LOOP_EXECUTION=true
          if [[ -n "$PROXY" ]]; then
            LOOP_EXECUTION=false
          else
            export PROXY="socks5://127.0.0.1:40000"
          fi
          while IFS= read -r line; do
            if [[ "$LOOP_EXECUTION" == "true" ]]; then
              warp-cli --accept-tos tunnel endpoint set "$line"
              sleep 30
            fi
            xvfb-run --server-args="-screen 0 1920x1080x24" python app.py +config=ci || true
            if [[ "$LOOP_EXECUTION" == "false" ]]; then
              break
            fi
          done < "iplist.txt"
      - uses: actions/upload-artifact@v4
        with:
          path: |
            *.log
            *.json
            tmp/
      - uses: ncipollo/release-action@v1
        with:
          repo: ${{ env.REPOSITORY }}
          artifacts: "*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
          token: ${{ secrets.PAT }}
