name: no-job

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:

env:
  REPOSITORY: "no-job"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          token: ${{ secrets.PAT }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra language-pack-zh-hans google-chrome-stable unzip curl
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install -r requirements.txt --upgrade
      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          tag: "zhipin"
          fileName: "*.json"
          token: ${{ secrets.PAT }}
      - uses: mdgreenwald/mozilla-sops-action@v1
      - run: sops -d config.toml.enc > config.toml
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - run: |
          wget https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-alpha-cc7823d.deb
          sudo dpkg -i mihomo-linux-amd64-alpha-cc7823d.deb
          sudo apt-get install -f
          curl -o config.yaml $MIHOMO_CONFIG
          sed -i 's/mode: Rule/mode: Global/' config.yaml
          sudo cp config.yaml /etc/mihomo
        env:
          MIHOMO_CONFIG: ${{ secrets.MIHOMO_CONFIG }}
      - run: |
          sudo systemd-run --no-ask-password --unit=mihomo-proxy mihomo -d /etc/mihomo
          sleep 12
          systemctl status mihomo-proxy.service
      - env:
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        continue-on-error: true
        run: |
          source .venv/bin/activate
          PROXY="http://127.0.0.1:7890" python zhipin_drission_page.py
      - uses: actions/upload-artifact@v4
        with:
          path: |
            zhipin/*.log
            zhipin/*.json
      - uses: ncipollo/release-action@v1
        with:
          repo: ${{ env.REPOSITORY }}
          artifacts: "*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
          token: ${{ secrets.PAT }}
