name: no-job

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  REPOSITORY: "no-job"

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          token: ${{ secrets.PAT }}
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: hynek/setup-cached-uv@v2
      - run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install -r requirements.txt --upgrade
      - uses: robinraju/release-downloader@v1
        continue-on-error: true
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          tag: "zhipin"
          fileName: "*.json"
          token: ${{ secrets.PAT }}
      - uses: mdgreenwald/mozilla-sops-action@v1
      - run: |
          sops --input-type dotenv --output-type dotenv -d .env.enc > .env
          sops -d config.toml.enc > config.toml
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - continue-on-error: true
        run: |
          source .venv/bin/activate
          python zhipin_drission_page.py
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.version }}
          path: |
            *.log
            *.json
            tmp/
      - uses: ncipollo/release-action@v1
        with:
          repo: ${{ env.REPOSITORY }}
          artifacts: "*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
          token: ${{ secrets.PAT }}
