name: Deploy paste-worker

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "yllhwa/FileWorker"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: |
          bun i
          bun run build
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: paste-worker
          directory: dist
          branch: main
          wranglerVersion: "3"
