name: Deploy sublink-worker

on:
  schedule:
    - cron: "0 18 * * 3"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "7Sageer/sublink-worker"
      - run: sed -i.bak "s/id = \"[0-9]*\"/id = \"$SUBLINK_KV_ID\"/" wrangler.toml
        env:
          SUBLINK_KV_ID: ${{ secrets.SUBLINK_KV_ID }}
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name sublink-worker
