name: zhipin

on:
  schedule:
    - cron: "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"
  workflow_dispatch:
    inputs:
      proxy:
        description: "Use proxy"
        required: false
        default: ""
        type: string
      manual:
        description: "Use manual"
        required: false
        default: false
        type: boolean

env:
  REPOSITORY: "no-job"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          token: ${{ secrets.PAT }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          cd zhipin
          uv pip install -r requirements.txt --upgrade
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - uses: robinraju/release-downloader@v1.10
        continue-on-error: true
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          tag: "zhipin"
          fileName: "*.json"
          out-file-path: "zhipin"
          token: ${{ secrets.PAT }}
      - run: |
          curl -o wireguard.sh https://raw.githubusercontent.com/aucub/actions/main/sh/wireguard.sh
          sudo chmod +x wireguard.sh
          sudo bash wireguard.sh
        if: ${{ !inputs.proxy }}
      - uses: mdgreenwald/mozilla-sops-action@v1
      - run: |
          cd zhipin
          sops -d config.toml.enc > config.toml
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - name: Run
        continue-on-error: true
        if: ${{ !inputs.manual }}
        env:
          STATE: ${{ vars.STATE }}
          CONFIG_URL: ${{ vars.CONFIG_URL }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          PROXY: ${{ inputs.proxy }}
        run: |
          source .venv/bin/activate
          cd zhipin
          python zhipinDP.py
      - name: Run manual
        continue-on-error: true
        if: ${{ inputs.manual }}
        env:
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          PROXY: ${{ inputs.proxy }}
        run: |
          cd zhipin
          curl -sSf https://sshx.io/get | sh -s run
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: |
            zhipin/*.txt
            zhipin/*.log
            zhipin/*.json
            zhipin/*/*.jsonl
      - uses: ncipollo/release-action@v1
        if: always()
        with:
          repo: ${{ env.REPOSITORY }}
          artifacts: "zhipin/*.json"
          allowUpdates: true
          replacesArtifacts: true
          tag: zhipin
          prerelease: true
          token: ${{ secrets.PAT }}
