name: zhipin-manual

on:
  workflow_dispatch:

env:
  REPOSITORY: "no-job"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          token: ${{ secrets.PAT }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r zhipin/requirements.txt
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Check the console scripts interface
        run: |
          seleniumbase
          sbase
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
          seleniumbase install uc_driver
      - name: Make sure pytest is working
        run: |
          echo "def test_1(): pass" > nothing.py
          pytest nothing.py
      - name: Make sure nosetests is working
        run: |
          echo "def test_2(): pass" > nothing2.py
          nosetests nothing2.py
      - uses: robinraju/release-downloader@v1.10
        continue-on-error: true
        with:
          repository: "${{ github.actor }}/${{ env.REPOSITORY }}"
          tag: "zhipin"
          fileName: "*.json"
          out-file-path: "zhipin"
          token: ${{ secrets.PAT }}
      - run: |
          sudo chmod +x sh/wireguard.sh
          sudo bash sh/wireguard.sh
        if: ${{ !vars.PROXY_URL }}
      - run: sudo cat zhipin/tool/hosts >> /etc/hosts
      - name: Run pytest
        env:
          DB_URL: ${{ secrets.DB_URL }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SAVED_COOKIES: ${{ secrets.SAVED_COOKIES }}
        run: |
          cd zhipin
          curl -sSf https://sshx.io/get | sh -s run
